dependencies:
  # command line stuff
  - click
  - coverage
  # reading rasters
  - gdal
  - pyshp
  - tqdm
  - pandas
  # RabbitMQ
  - pika
  # image work
  - pillow
  - psycopg
  # Data validation
  - pydantic
  # daryl's helper library, there are downstream users, so discipline please!
  - pyiem>=1.26.0
  # Fast geojson reading
  - pyogrio
  # For testing
  - pytest
  - pytest-cov
  # For testing
  - pytest-httpx>=0.35.0
  - pytest-runner
  # interpolation
  - scipy
  # GIS work
  - shapely
  - sqlalchemy
  # daily auto-tweeter
  - tweepy
  - reportlab
